ALTER TABLE userr
    ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE project
    ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE task
    ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE meeting
    ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;