version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projectmanagement
    ports:
      - "5432:5432"

  payara:
    image: project_management
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "4848:4848"